// ═══════════════════════════════════════════
// DONNÉES COMPLÈTES — Islam Authentique v4
// ═══════════════════════════════════════════

const HADITHS = [
  // TAWHID
  {id:1,ar:"إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ",fr:"Les actes ne valent que par les intentions.",n:"Umar Ibn Al-Khattab ر",b:"Sahih Al-Bukhari",num:1,a:"Sahih",ref:"Bukhari n°1",th:"Niyyah"},
  {id:2,ar:"أَعْظَمُ الذُّنُوبِ أَنْ تَجْعَلَ لِلَّهِ نِدًّا وَهُوَ خَلَقَكَ",fr:"Le plus grand des péchés est que tu fasses un rival à Allah alors qu'Il t'a créé.",n:"Abdullah Ibn Masud ر",b:"Sahih Al-Bukhari",num:6001,a:"Sahih",ref:"Bukhari n°6001",th:"Tawhid"},
  {id:3,ar:"مَنْ مَاتَ وَهُوَ يَعْلَمُ أَنَّهُ لَا إِلَٰهَ إِلَّا اللهُ دَخَلَ الْجَنَّةَ",fr:"Quiconque meurt en sachant qu'il n'y a de divinité qu'Allah entrera au Paradis.",n:"Abu Dharr Al-Ghifari ر",b:"Sahih Muslim",num:26,a:"Sahih",ref:"Muslim n°26",th:"Tawhid"},
  {id:4,ar:"الدُّعَاءُ هُوَ الْعِبَادَةُ",fr:"La supplication (Du'a), c'est l'adoration.",n:"An-Nu'man Ibn Bashir ر",b:"Sunan At-Tirmidhi",num:2969,a:"Sahih",ref:"Silsilah n°65",th:"Du'a"},
  {id:5,ar:"لَعَنَ اللهُ مَنِ اتَّخَذَ قَبْرَ نَبِيِّهِ مَسْجِدًا",fr:"Allah a maudit quiconque prend la tombe de son prophète comme lieu de prière.",n:"Aïcha ر",b:"Sahih Al-Bukhari",num:435,a:"Sahih",ref:"Bukhari n°435",th:"Tawhid"},
  // BID'AH
  {id:6,ar:"مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ",fr:"Quiconque introduit dans notre religion quelque chose qui n'en fait pas partie, cela sera rejeté.",n:"Aïcha ر",b:"Sahih Al-Bukhari",num:2697,a:"Sahih",ref:"Bukhari n°2697",th:"Bid'ah"},
  {id:7,ar:"عَلَيْكُمْ بِسُنَّتِي وَسُنَّةِ الْخُلَفَاءِ الرَّاشِدِينَ",fr:"Tenez-vous à ma Sunnah et à la Sunnah des califes bien guidés après moi.",n:"Al-Irbad Ibn Sariya ر",b:"Sunan Abu Dawud",num:4607,a:"Sahih",ref:"Silsilah n°2735",th:"Sunnah"},
  {id:8,ar:"خَيْرُ الْقُرُونِ قَرْنِي ثُمَّ الَّذِينَ يَلُونَهُمْ ثُمَّ الَّذِينَ يَلُونَهُمْ",fr:"La meilleure génération est la mienne, puis celle qui suit, puis celle qui suit.",n:"Abdullah Ibn Masud ر",b:"Sahih Al-Bukhari",num:3651,a:"Sahih",ref:"Bukhari n°3651",th:"Salaf"},
  {id:9,ar:"مَنْ عَمِلَ عَمَلًا لَيْسَ عَلَيْهِ أَمْرُنَا فَهُوَ رَدٌّ",fr:"Quiconque accomplit une œuvre sur laquelle nous n'avons pas donné d'ordre, elle sera rejetée.",n:"Aïcha ر",b:"Sahih Muslim",num:1718,a:"Sahih",ref:"Muslim n°1718",th:"Bid'ah"},
  {id:10,ar:"كُلُّ بِدْعَةٍ ضَلَالَةٌ وَكُلُّ ضَلَالَةٍ فِي النَّارِ",fr:"Toute innovation est un égarement et tout égarement conduit au Feu.",n:"Jabir Ibn Abdillah ر",b:"Sahih Muslim",num:867,a:"Sahih",ref:"Muslim n°867",th:"Bid'ah"},
  // IMAN
  {id:11,ar:"الدِّينُ النَّصِيحَةُ",fr:"La religion c'est la sincérité.",n:"Tamim Ad-Dari ر",b:"Sahih Muslim",num:55,a:"Sahih",ref:"Muslim n°55",th:"Nasiha"},
  {id:12,ar:"بُنِيَ الإِسْلَامُ عَلَى خَمْسٍ",fr:"L'Islam est bâti sur cinq piliers : le témoignage, la prière, la zakat, le jeûne et le hajj.",n:"Ibn Umar ر",b:"Sahih Al-Bukhari",num:8,a:"Sahih",ref:"Bukhari n°8",th:"Pilliers"},
  {id:13,ar:"لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",fr:"Aucun de vous n'est croyant tant qu'il n'aime pas pour son frère ce qu'il aime pour lui-même.",n:"Anas Ibn Malik ر",b:"Sahih Al-Bukhari",num:13,a:"Sahih",ref:"Bukhari n°13",th:"Fraternité"},
  {id:14,ar:"اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ",fr:"Crains Allah où que tu sois, fais suivre une mauvaise action d'une bonne qui l'effacera, et traite les gens avec un bon comportement.",n:"Abu Dharr ر",b:"Sunan At-Tirmidhi",num:1987,a:"Hasan Sahih",ref:"Silsilah n°1373",th:"Taqwa"},
  {id:15,ar:"الطَّهُورُ شَطْرُ الإِيمَانِ",fr:"La pureté est la moitié de la foi.",n:"Abu Malik Al-Ash'ari ر",b:"Sahih Muslim",num:223,a:"Sahih",ref:"Muslim n°223",th:"Taharah"},
  // CORAN & ILM
  {id:16,ar:"خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",fr:"Le meilleur d'entre vous est celui qui apprend le Coran et l'enseigne.",n:"Uthman Ibn Affan ر",b:"Sahih Al-Bukhari",num:5027,a:"Sahih",ref:"Bukhari n°5027",th:"Coran"},
  {id:17,ar:"مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ",fr:"Quiconque emprunte un chemin pour y chercher de la connaissance, Allah lui facilite un chemin vers le Paradis.",n:"Abu Hurayra ر",b:"Sahih Muslim",num:2699,a:"Sahih",ref:"Muslim n°2699",th:"'Ilm"},
  {id:18,ar:"طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ",fr:"La recherche de la connaissance est une obligation pour tout musulman.",n:"Anas Ibn Malik ر",b:"Sunan Ibn Majah",num:224,a:"Sahih",ref:"Silsilah n°342",th:"'Ilm"},
  {id:19,ar:"إِذَا مَاتَ الإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ",fr:"Quand l'être humain meurt, ses actes s'interrompent sauf trois : une aumône continue, une connaissance dont on bénéficie, ou un enfant pieux qui fait du du'a pour lui.",n:"Abu Hurayra ر",b:"Sahih Muslim",num:1631,a:"Sahih",ref:"Muslim n°1631",th:"'Ilm"},
  {id:20,ar:"مَنْ يُرِدِ اللهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ",fr:"Quand Allah veut du bien à quelqu'un, Il lui donne la compréhension de la religion.",n:"Mu'awiya ر",b:"Sahih Al-Bukhari",num:71,a:"Sahih",ref:"Bukhari n°71",th:"'Ilm"},
  // SALAT
  {id:21,ar:"صَلُّوا كَمَا رَأَيْتُمُونِي أُصَلِّي",fr:"Priez comme vous m'avez vu prier.",n:"Malik Ibn Al-Huwayrit ر",b:"Sahih Al-Bukhari",num:631,a:"Sahih",ref:"Bukhari n°631",th:"Salat"},
  {id:22,ar:"أَوَّلُ مَا يُحَاسَبُ بِهِ الْعَبْدُ يَوْمَ الْقِيَامَةِ الصَّلَاةُ",fr:"La première chose dont le serviteur sera rendu compte au Jour du Jugement, c'est la prière.",n:"Abu Hurayra ر",b:"Sunan At-Tirmidhi",num:413,a:"Sahih",ref:"Silsilah n°1358",th:"Salat"},
  {id:23,ar:"الصَّلَاةُ عِمَادُ الدِّينِ",fr:"La prière est le pilier de la religion.",n:"Mu'adh Ibn Jabal ر",b:"Musnad Ahmad",num:22016,a:"Sahih",ref:"Silsilah n°1574",th:"Salat"},
  // AKHLAQ
  {id:24,ar:"إِنَّمَا بُعِثْتُ لِأُتَمِّمَ مَكَارِمَ الأَخْلَاقِ",fr:"Je n'ai été envoyé que pour parfaire les nobles caractères.",n:"Abu Hurayra ر",b:"Muwatta Malik",num:1614,a:"Sahih",ref:"Silsilah n°45",th:"Akhlaq"},
  {id:25,ar:"مَنْ كَانَ يُؤْمِنُ بِاللهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",fr:"Que celui qui croit en Allah et au Jour Dernier dise quelque chose de bien ou qu'il se taise.",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:6018,a:"Sahih",ref:"Bukhari n°6018",th:"Akhlaq"},
  {id:26,ar:"إِنَّ اللهَ لَا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",fr:"Allah ne regarde pas vos apparences ni vos richesses, mais Il regarde vos cœurs et vos actes.",n:"Abu Hurayra ر",b:"Sahih Muslim",num:2564,a:"Sahih",ref:"Muslim n°2564",th:"Akhlaq"},
  {id:27,ar:"الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",fr:"Le musulman est celui dont les musulmans sont préservés de sa langue et de sa main.",n:"Abdullah Ibn Umar ر",b:"Sahih Al-Bukhari",num:10,a:"Sahih",ref:"Bukhari n°10",th:"Akhlaq"},
  {id:28,ar:"لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",fr:"Le fort n'est pas celui qui met les autres à terre. Le fort est celui qui se maîtrise quand il est en colère.",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:6114,a:"Sahih",ref:"Bukhari n°6114",th:"Akhlaq"},
  {id:29,ar:"لَا تَغْضَبْ",fr:"Ne te mets pas en colère. (répété 3 fois par le Prophète ﷺ)",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:6116,a:"Sahih",ref:"Bukhari n°6116",th:"Akhlaq"},
  {id:30,ar:"إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ وَأَقْرَبِكُمْ مِنِّي مَجْلِسًا يَوْمَ الْقِيَامَةِ أَحَاسِنَكُمْ أَخْلَاقًا",fr:"Parmi vous, les plus aimés de moi et les plus proches de moi le Jour du Jugement seront ceux qui ont le meilleur caractère.",n:"Jabir ر",b:"Sunan At-Tirmidhi",num:2018,a:"Sahih",ref:"Silsilah n°791",th:"Akhlaq"},
  // DHIKR & DUA
  {id:31,ar:"سُبْحَانَ اللهِ وَبِحَمْدِهِ سُبْحَانَ اللهِ الْعَظِيمِ",fr:"Deux paroles légères sur la langue, lourdes dans la balance, chères au Miséricordieux : Subhan Allah wa bihamdihi, Subhan Allahil Azim.",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:6682,a:"Sahih",ref:"Bukhari n°6682",th:"Dhikr"},
  {id:32,ar:"أَفْضَلُ الذِّكْرِ لَا إِلَٰهَ إِلَّا اللهُ",fr:"Le meilleur des dhikr est : Lâ ilâha illallâh.",n:"Jabir Ibn Abdillah ر",b:"Sunan At-Tirmidhi",num:3383,a:"Sahih",ref:"Silsilah n°1498",th:"Dhikr"},
  {id:33,ar:"الدُّعَاءُ مُخُّ الْعِبَادَةِ",fr:"La supplication est la moelle de l'adoration.",n:"Anas Ibn Malik ر",b:"Sunan At-Tirmidhi",num:3371,a:"Sahih",ref:"Silsilah n°66",th:"Du'a"},
  // SABR
  {id:34,ar:"عَجَبًا لِأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ",fr:"Étonnante est la situation du croyant ! Tout ce qui lui arrive est bon pour lui.",n:"Suhaib ر",b:"Sahih Muslim",num:2999,a:"Sahih",ref:"Muslim n°2999",th:"Sabr"},
  {id:35,ar:"مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلَا وَصَبٍ وَلَا هَمٍّ وَلَا حَزَنٍ إِلَّا كَفَّرَ اللهُ بِهِ",fr:"Aucune fatigue, maladie, souci ou tristesse ne touche le musulman sans qu'Allah n'expie par cela ses péchés.",n:"Abu Sa'id et Abu Hurayra ر",b:"Sahih Al-Bukhari",num:5641,a:"Sahih",ref:"Bukhari n°5641",th:"Sabr"},
  {id:36,ar:"احْرِصْ عَلَى مَا يَنْفَعُكَ وَاسْتَعِنْ بِاللهِ وَلَا تَعْجَزْ",fr:"Sois avide de ce qui te profite, cherche l'aide d'Allah et ne sois pas impuissant.",n:"Abu Hurayra ر",b:"Sahih Muslim",num:2664,a:"Sahih",ref:"Muslim n°2664",th:"Tawakkul"},
  // FAMILLE
  {id:37,ar:"كُلُّكُمْ رَاعٍ وَكُلُّكُمْ مَسْؤُولٌ عَنْ رَعِيَّتِهِ",fr:"Vous êtes tous des bergers et chacun de vous est responsable de son troupeau.",n:"Abdullah Ibn Umar ر",b:"Sahih Al-Bukhari",num:893,a:"Sahih",ref:"Bukhari n°893",th:"Famille"},
  {id:38,ar:"الْجَنَّةُ تَحْتَ أَقْدَامِ الأُمَّهَاتِ",fr:"Le Paradis est sous les pieds des mères.",n:"Mu'awiyah Ibn Jahima ر",b:"Sunan An-Nasa'i",num:3104,a:"Sahih",ref:"Silsilah n°593",th:"Famille"},
  {id:39,ar:"خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ",fr:"Le meilleur d'entre vous est celui qui est le meilleur avec sa famille.",n:"Aïcha ر",b:"Sunan At-Tirmidhi",num:3895,a:"Sahih",ref:"Silsilah n°285",th:"Famille"},
  // RAMADAN & SIYAM
  {id:40,ar:"مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",fr:"Quiconque jeûne le Ramadan avec foi et en espérant la récompense, ses péchés passés lui seront pardonnés.",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:38,a:"Sahih",ref:"Bukhari n°38",th:"Ramadan"},
  {id:41,ar:"الصَّوْمُ جُنَّةٌ",fr:"Le jeûne est un bouclier.",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:1894,a:"Sahih",ref:"Bukhari n°1894",th:"Siyam"},
  // SADAQA
  {id:42,ar:"الصَّدَقَةُ تُطْفِئُ الْخَطِيئَةَ كَمَا يُطْفِئُ الْمَاءُ النَّارَ",fr:"L'aumône éteint le péché comme l'eau éteint le feu.",n:"Mu'adh Ibn Jabal ر",b:"Sunan At-Tirmidhi",num:2616,a:"Sahih",ref:"Silsilah n°928",th:"Sadaqa"},
  {id:43,ar:"مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ",fr:"Une aumône ne diminue jamais un patrimoine.",n:"Abu Hurayra ر",b:"Sahih Muslim",num:2588,a:"Sahih",ref:"Muslim n°2588",th:"Sadaqa"},
  // MORT & AKHIRA
  {id:44,ar:"أَكْثِرُوا ذِكْرَ هَاذِمِ اللَّذَّاتِ",fr:"Évoquez souvent le destructeur des plaisirs (la mort).",n:"Abu Hurayra ر",b:"Sunan At-Tirmidhi",num:2307,a:"Sahih",ref:"Silsilah n°1421",th:"Mort"},
  {id:45,ar:"الْكَيِّسُ مَنْ دَانَ نَفْسَهُ وَعَمِلَ لِمَا بَعْدَ الْمَوْتِ",fr:"L'intelligent est celui qui soumet son âme et œuvre pour ce qui vient après la mort.",n:"Shaddad Ibn Aws ر",b:"Sunan At-Tirmidhi",num:2459,a:"Sahih",ref:"Silsilah n°1368",th:"Akhira"},
  // FRATERNITE
  {id:46,ar:"لَا تَحَاسَدُوا وَلَا تَنَاجَشُوا وَلَا تَبَاغَضُوا",fr:"Ne vous jalousez pas, ne vous sous-enchérissez pas, ne vous haïssez pas.",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:6064,a:"Sahih",ref:"Bukhari n°6064",th:"Akhlaq"},
  {id:47,ar:"الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا",fr:"Le croyant est au croyant comme un édifice dont chaque partie renforce les autres.",n:"Abu Musa ر",b:"Sahih Al-Bukhari",num:481,a:"Sahih",ref:"Bukhari n°481",th:"Fraternité"},
  // HADITH
  {id:48,ar:"نَضَّرَ اللهُ امْرَأً سَمِعَ مِنَّا حَدِيثًا فَحَفِظَهُ حَتَّى يُبَلِّغَهُ غَيْرَهُ",fr:"Qu'Allah illumine celui qui a entendu un hadith de nous, l'a mémorisé et l'a transmis.",n:"Ibn Masud ر",b:"Sunan At-Tirmidhi",num:2656,a:"Sahih",ref:"Silsilah n°404",th:"Hadith"},
  {id:49,ar:"مَنْ كَذَبَ عَلَيَّ مُتَعَمِّدًا فَلْيَتَبَوَّأْ مَقْعَدَهُ مِنَ النَّارِ",fr:"Quiconque ment sur moi intentionnellement, qu'il prépare sa place dans le Feu.",n:"Abu Hurayra ر",b:"Sahih Al-Bukhari",num:110,a:"Sahih",ref:"Bukhari n°110",th:"Hadith"},
  // DIVERS
  {id:50,ar:"إِنَّ اللهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الأَمْرِ كُلِّهِ",fr:"Allah est doux et Il aime la douceur en toute chose.",n:"Aïcha ر",b:"Sahih Al-Bukhari",num:6927,a:"Sahih",ref:"Bukhari n°6927",th:"Rifq"},
  {id:51,ar:"إِنَّ اللهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ",fr:"Allah aime que lorsque l'un d'entre vous accomplit une œuvre, il l'accomplisse parfaitement.",n:"Aïcha ر",b:"Mu'jam Al-Awsat",num:897,a:"Sahih",ref:"Silsilah n°1113",th:"Itqan"},
  {id:52,ar:"الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ",fr:"Le croyant fort est meilleur et plus aimé d'Allah que le croyant faible, mais en chacun il y a du bien.",n:"Abu Hurayra ر",b:"Sahih Muslim",num:2664,a:"Sahih",ref:"Muslim n°2664",th:"Force"},
  {id:53,ar:"يَسِّرُوا وَلَا تُعَسِّرُوا وَبَشِّرُوا وَلَا تُنَفِّرُوا",fr:"Facilitez et ne rendez pas difficile, annoncez une bonne nouvelle et ne faites pas fuir.",n:"Anas Ibn Malik ر",b:"Sahih Al-Bukhari",num:69,a:"Sahih",ref:"Bukhari n°69",th:"Yusr"},
  {id:54,ar:"الْحَلَالُ بَيِّنٌ وَالْحَرَامُ بَيِّنٌ وَبَيْنَهُمَا أُمُورٌ مُشْتَبِهَاتٌ",fr:"Le licite est clair et l'illicite est clair, et entre les deux il y a des choses douteuses.",n:"An-Nu'man Ibn Bashir ر",b:"Sahih Al-Bukhari",num:52,a:"Sahih",ref:"Bukhari n°52",th:"Halal/Haram"},
  {id:55,ar:"مَنْ حَسُنَ إِسْلَامُ الْمَرْءِ تَرْكُهُ مَا لَا يَعْنِيهِ",fr:"Parmi la beauté de l'Islam d'une personne : délaisser ce qui ne la concerne pas.",n:"Abu Hurayra ر",b:"Sunan At-Tirmidhi",num:2317,a:"Sahih",ref:"Silsilah n°1228",th:"Akhlaq"},
  // ARBA'IN AN-NAWAWI (sélection)
  {id:56,ar:"إِنَّ اللهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَيْءٍ",fr:"Allah a prescrit l'excellence (ihsan) en toute chose.",n:"Shaddad Ibn Aws ر",b:"Sahih Muslim",num:1955,a:"Sahih",ref:"Muslim n°1955 — Arba'in n°17",th:"Ihsan"},
  {id:57,ar:"لَا ضَرَرَ وَلَا ضِرَارَ",fr:"Pas de préjudice et pas de nuisance (en Islam).",n:"Ibn Abbas ر",b:"Sunan Ibn Majah",num:2341,a:"Sahih",ref:"Silsilah n°250 — Arba'in n°32",th:"Fiqh"},
  {id:58,ar:"مَنْ رَأَى مِنْكُمْ مُنْكَرًا فَلْيُغَيِّرْهُ بِيَدِهِ",fr:"Quiconque parmi vous voit un acte répréhensible, qu'il le change de sa main, sinon de sa langue, sinon de son cœur — et c'est le plus faible de la foi.",n:"Abu Sa'id Al-Khudri ر",b:"Sahih Muslim",num:49,a:"Sahih",ref:"Muslim n°49 — Arba'in n°34",th:"Amr bil Ma'ruf"},
  {id:59,ar:"أَحَبُّ الأَعْمَالِ إِلَى اللهِ أَدْوَمُهَا وَإِنْ قَلَّ",fr:"Les actes les plus aimés d'Allah sont les plus constants, même s'ils sont peu nombreux.",n:"Aïcha ر",b:"Sahih Al-Bukhari",num:6464,a:"Sahih",ref:"Bukhari n°6464",th:"Istiqama"},
  {id:60,ar:"بَدَأَ الإِسْلَامُ غَرِيبًا وَسَيَعُودُ غَرِيبًا فَطُوبَى لِلْغُرَبَاءِ",fr:"L'Islam a commencé étranger et il redeviendra étranger. Bienheureux les étrangers !",n:"Abu Hurayra ر",b:"Sahih Muslim",num:145,a:"Sahih",ref:"Muslim n°145",th:"Ghuraba"},
];

const ASMA_HUSNA = [
  {n:1,ar:"اللَّهُ",fr:"Allah",d:"Le nom suprême qui englobe tous les attributs divins."},
  {n:2,ar:"الرَّحْمَٰنُ",fr:"Ar-Rahman",d:"Le Tout Miséricordieux — dont la miséricorde englobe toutes choses."},
  {n:3,ar:"الرَّحِيمُ",fr:"Ar-Rahim",d:"Le Très Miséricordieux — dont la miséricorde est spéciale pour les croyants."},
  {n:4,ar:"الْمَلِكُ",fr:"Al-Malik",d:"Le Roi absolu de toute chose."},
  {n:5,ar:"الْقُدُّوسُ",fr:"Al-Quddus",d:"Le Pur, exempt de tout défaut et imperfection."},
  {n:6,ar:"السَّلَامُ",fr:"As-Salam",d:"La Paix, source de toute paix et sécurité."},
  {n:7,ar:"الْمُؤْمِنُ",fr:"Al-Mu'min",d:"Celui qui donne la foi et la sécurité."},
  {n:8,ar:"الْمُهَيْمِنُ",fr:"Al-Muhaymin",d:"Le Gardien suprême, le Protecteur."},
  {n:9,ar:"الْعَزِيزُ",fr:"Al-Aziz",d:"Le Tout-Puissant, l'Irrésistible."},
  {n:10,ar:"الْجَبَّارُ",fr:"Al-Jabbar",d:"Le Contraignant, Celui dont la volonté s'impose."},
  {n:11,ar:"الْمُتَكَبِّرُ",fr:"Al-Mutakabbir",d:"Le Majestueux, Supérieur à toute chose."},
  {n:12,ar:"الْخَالِقُ",fr:"Al-Khaliq",d:"Le Créateur de toutes choses."},
  {n:13,ar:"الْبَارِئُ",fr:"Al-Bari'",d:"Celui qui donne la forme et la structure."},
  {n:14,ar:"الْمُصَوِّرُ",fr:"Al-Musawwir",d:"Celui qui façonne les formes comme Il le veut."},
  {n:15,ar:"الْغَفَّارُ",fr:"Al-Ghaffar",d:"Celui qui pardonne encore et encore."},
  {n:16,ar:"الْقَهَّارُ",fr:"Al-Qahhar",d:"Le Dominateur absolu."},
  {n:17,ar:"الْوَهَّابُ",fr:"Al-Wahhab",d:"Le Grand Donateur, qui offre sans contrepartie."},
  {n:18,ar:"الرَّزَّاقُ",fr:"Ar-Razzaq",d:"Le Pourvoyeur de toute subsistance."},
  {n:19,ar:"الْفَتَّاحُ",fr:"Al-Fattah",d:"Celui qui ouvre et délivre."},
  {n:20,ar:"الْعَلِيمُ",fr:"Al-Alim",d:"L'Omniscient, qui sait tout."},
  {n:21,ar:"الْقَابِضُ",fr:"Al-Qabid",d:"Celui qui resserre, qui retient."},
  {n:22,ar:"الْبَاسِطُ",fr:"Al-Basit",d:"Celui qui élargit et répand."},
  {n:23,ar:"الْخَافِضُ",fr:"Al-Khafid",d:"Celui qui abaisse."},
  {n:24,ar:"الرَّافِعُ",fr:"Ar-Rafi'",d:"Celui qui élève."},
  {n:25,ar:"الْمُعِزُّ",fr:"Al-Mu'izz",d:"Celui qui honore."},
  {n:26,ar:"الْمُذِلُّ",fr:"Al-Mudhill",d:"Celui qui humilie."},
  {n:27,ar:"السَّمِيعُ",fr:"As-Sami'",d:"Celui qui entend tout."},
  {n:28,ar:"الْبَصِيرُ",fr:"Al-Basir",d:"Celui qui voit tout."},
  {n:29,ar:"الْحَكَمُ",fr:"Al-Hakam",d:"Le Juge suprême."},
  {n:30,ar:"الْعَدْلُ",fr:"Al-Adl",d:"Le Parfaitement Juste."},
  {n:31,ar:"اللَّطِيفُ",fr:"Al-Latif",d:"Le Subtil, le Doux, le Bienveillant."},
  {n:32,ar:"الْخَبِيرُ",fr:"Al-Khabir",d:"Le Parfaitement Informé."},
  {n:33,ar:"الْحَلِيمُ",fr:"Al-Halim",d:"Le Clément, le Longanime."},
  {n:34,ar:"الْعَظِيمُ",fr:"Al-Azim",d:"L'Immense, le Magnifique."},
  {n:35,ar:"الْغَفُورُ",fr:"Al-Ghafur",d:"Le Grand Pardonneur."},
  {n:36,ar:"الشَّكُورُ",fr:"Ash-Shakur",d:"Le Très Reconnaissant."},
  {n:37,ar:"الْعَلِيُّ",fr:"Al-Aliyy",d:"Le Très-Haut."},
  {n:38,ar:"الْكَبِيرُ",fr:"Al-Kabir",d:"Le Grand."},
  {n:39,ar:"الْحَفِيظُ",fr:"Al-Hafiz",d:"Le Gardien, le Préservateur."},
  {n:40,ar:"الْمُقِيتُ",fr:"Al-Muqit",d:"Le Sustentateur."},
  {n:41,ar:"الْحَسِيبُ",fr:"Al-Hasib",d:"Celui qui suffit, le Comptable."},
  {n:42,ar:"الْجَلِيلُ",fr:"Al-Jalil",d:"Le Majestueux."},
  {n:43,ar:"الْكَرِيمُ",fr:"Al-Karim",d:"Le Très Généreux."},
  {n:44,ar:"الرَّقِيبُ",fr:"Ar-Raqib",d:"Le Vigilant, l'Observateur."},
  {n:45,ar:"الْمُجِيبُ",fr:"Al-Mujib",d:"Celui qui répond aux supplications."},
  {n:46,ar:"الْوَاسِعُ",fr:"Al-Wasi'",d:"Le Vaste, l'Immense."},
  {n:47,ar:"الْحَكِيمُ",fr:"Al-Hakim",d:"Le Sage parfait."},
  {n:48,ar:"الْوَدُودُ",fr:"Al-Wadud",d:"Le Très Aimant."},
  {n:49,ar:"الْمَجِيدُ",fr:"Al-Majid",d:"Le Glorieux."},
  {n:50,ar:"الْبَاعِثُ",fr:"Al-Ba'ith",d:"Celui qui ressuscite."},
  {n:51,ar:"الشَّهِيدُ",fr:"Ash-Shahid",d:"Le Témoin."},
  {n:52,ar:"الْحَقُّ",fr:"Al-Haqq",d:"La Vérité absolue."},
  {n:53,ar:"الْوَكِيلُ",fr:"Al-Wakil",d:"Le Garant, Celui en qui on se confie."},
  {n:54,ar:"الْقَوِيُّ",fr:"Al-Qawiyy",d:"Le Tout-Puissant."},
  {n:55,ar:"الْمَتِينُ",fr:"Al-Matin",d:"Le Solide, le Ferme."},
  {n:56,ar:"الْوَلِيُّ",fr:"Al-Waliyy",d:"Le Protecteur, l'Allié."},
  {n:57,ar:"الْحَمِيدُ",fr:"Al-Hamid",d:"Le Digne de toute louange."},
  {n:58,ar:"الْمُحْصِي",fr:"Al-Muhsi",d:"Celui qui dénombre tout."},
  {n:59,ar:"الْمُبْدِئُ",fr:"Al-Mubdi'",d:"Celui qui commence la création."},
  {n:60,ar:"الْمُعِيدُ",fr:"Al-Mu'id",d:"Celui qui renouvelle la création."},
  {n:61,ar:"الْمُحْيِي",fr:"Al-Muhyi",d:"Celui qui donne la vie."},
  {n:62,ar:"الْمُمِيتُ",fr:"Al-Mumit",d:"Celui qui donne la mort."},
  {n:63,ar:"الْحَيُّ",fr:"Al-Hayy",d:"Le Vivant éternel."},
  {n:64,ar:"الْقَيُّومُ",fr:"Al-Qayyum",d:"Celui qui subsiste par Lui-même et fait subsister tout."},
  {n:65,ar:"الْوَاجِدُ",fr:"Al-Wajid",d:"Celui qui trouve tout ce qu'Il veut."},
  {n:66,ar:"الْمَاجِدُ",fr:"Al-Majid",d:"Le Noble, le Généreux."},
  {n:67,ar:"الْوَاحِدُ",fr:"Al-Wahid",d:"L'Unique."},
  {n:68,ar:"الأَحَدُ",fr:"Al-Ahad",d:"L'Un, sans pareil ni associé."},
  {n:69,ar:"الصَّمَدُ",fr:"As-Samad",d:"Le Seul à être imploré, dont tout dépend."},
  {n:70,ar:"الْقَادِرُ",fr:"Al-Qadir",d:"Le Tout-Puissant, Capable de tout."},
  {n:71,ar:"الْمُقْتَدِرُ",fr:"Al-Muqtadir",d:"Le Prévalant, dont la puissance est totale."},
  {n:72,ar:"الْمُقَدِّمُ",fr:"Al-Muqaddim",d:"Celui qui avance."},
  {n:73,ar:"الْمُؤَخِّرُ",fr:"Al-Mu'akhkhir",d:"Celui qui reporte."},
  {n:74,ar:"الأَوَّلُ",fr:"Al-Awwal",d:"Le Premier, sans commencement."},
  {n:75,ar:"الآخِرُ",fr:"Al-Akhir",d:"Le Dernier, sans fin."},
  {n:76,ar:"الظَّاهِرُ",fr:"Az-Zahir",d:"L'Apparent, Manifesté."},
  {n:77,ar:"الْبَاطِنُ",fr:"Al-Batin",d:"Le Caché, l'Intérieur."},
  {n:78,ar:"الْوَالِي",fr:"Al-Wali",d:"Le Souverain, le Gouverneur."},
  {n:79,ar:"الْمُتَعَالِي",fr:"Al-Muta'ali",d:"Le Très-Élevé au-dessus de tout."},
  {n:80,ar:"الْبَرُّ",fr:"Al-Barr",d:"Le Bienfaisant, le Bon."},
  {n:81,ar:"التَّوَّابُ",fr:"At-Tawwab",d:"Celui qui accepte le repentir."},
  {n:82,ar:"الْمُنْتَقِمُ",fr:"Al-Muntaqim",d:"Celui qui se venge des injustes."},
  {n:83,ar:"الْعَفُوُّ",fr:"Al-Afuww",d:"Celui qui efface les fautes."},
  {n:84,ar:"الرَّؤُوفُ",fr:"Ar-Ra'uf",d:"Le Très Compatissant."},
  {n:85,ar:"مَالِكُ الْمُلْكِ",fr:"Malik Al-Mulk",d:"Le Maître de la Royauté."},
  {n:86,ar:"ذُو الْجَلَالِ وَالإِكْرَامِ",fr:"Dhu Al-Jalal wal-Ikram",d:"Le Possesseur de Majesté et de Générosité."},
  {n:87,ar:"الْمُقْسِطُ",fr:"Al-Muqsit",d:"Le Juste, l'Équitable."},
  {n:88,ar:"الْجَامِعُ",fr:"Al-Jami'",d:"Celui qui rassemble."},
  {n:89,ar:"الْغَنِيُّ",fr:"Al-Ghani",d:"Le Riche, l'Indépendant."},
  {n:90,ar:"الْمُغْنِي",fr:"Al-Mughni",d:"Celui qui enrichit."},
  {n:91,ar:"الْمَانِعُ",fr:"Al-Mani'",d:"Celui qui empêche et protège."},
  {n:92,ar:"الضَّارُّ",fr:"Ad-Darr",d:"Celui qui peut causer du tort."},
  {n:93,ar:"النَّافِعُ",fr:"An-Nafi'",d:"Celui qui profite."},
  {n:94,ar:"النُّورُ",fr:"An-Nur",d:"La Lumière."},
  {n:95,ar:"الْهَادِي",fr:"Al-Hadi",d:"Celui qui guide."},
  {n:96,ar:"الْبَدِيعُ",fr:"Al-Badi'",d:"Le Créateur incomparable."},
  {n:97,ar:"الْبَاقِي",fr:"Al-Baqi",d:"L'Éternel, qui demeure."},
  {n:98,ar:"الْوَارِثُ",fr:"Al-Warith",d:"L'Héritier de toutes choses."},
  {n:99,ar:"الرَّشِيدُ",fr:"Ar-Rashid",d:"Celui qui guide sur le droit chemin."},
];

const DUA = [
  // MATIN & SOIR
  {id:'d1',cat:'Matin & Soir',t:'Du\'a du matin',ar:'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ',fr:'Nous sommes entrés dans le matin et le Royaume appartient à Allah, et toute louange est à Allah.',ref:'Muslim n°2723'},
  {id:'d2',cat:'Matin & Soir',t:'Sayyid Al-Istighfar',ar:'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ',fr:'Ô Allah, Tu es mon Seigneur. Il n\'y a de divinité qu\'Toi. Tu m\'as créé et je suis Ton serviteur.',ref:'Bukhari n°6306'},
  // SOMMEIL
  {id:'d3',cat:'Sommeil',t:'Avant de dormir',ar:'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',fr:'En Ton nom, Ô Allah, je meurs et je vis.',ref:'Bukhari n°6324'},
  {id:'d4',cat:'Sommeil',t:'Au réveil',ar:'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',fr:'Louange à Allah qui nous a redonné la vie après nous avoir fait mourir, et c\'est vers Lui la résurrection.',ref:'Bukhari n°6312'},
  {id:'d5',cat:'Sommeil',t:'Cauchemar',ar:'أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ غَضَبِهِ وَعِقَابِهِ',fr:'Je cherche refuge auprès des paroles parfaites d\'Allah contre Sa colère et Son châtiment.',ref:'Muslim n°2714'},
  // REPAS
  {id:'d6',cat:'Repas',t:'Avant de manger',ar:'بِسْمِ اللهِ',fr:'Au nom d\'Allah.',ref:'Abu Dawud n°3767'},
  {id:'d7',cat:'Repas',t:'Après le repas',ar:'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',fr:'Louange à Allah qui nous a nourris, abreuvés et nous a faits musulmans.',ref:'Abu Dawud n°3850'},
  {id:'d8',cat:'Repas',t:'Si on oublie de dire Bismillah',ar:'بِسْمِ اللهِ أَوَّلَهُ وَآخِرَهُ',fr:'Au nom d\'Allah au début et à la fin.',ref:'Abu Dawud n°3767'},
  // MAISON
  {id:'d9',cat:'Maison',t:'En entrant',ar:'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلَجِ وَخَيْرَ الْمَخْرَجِ',fr:'Ô Allah, je Te demande le bien de l\'entrée et le bien de la sortie.',ref:'Abu Dawud n°5096'},
  {id:'d10',cat:'Maison',t:'En sortant',ar:'بِسْمِ اللهِ تَوَكَّلْتُ عَلَى اللهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ',fr:'Au nom d\'Allah, je me confie à Allah, il n\'y a de puissance et de force qu\'en Allah.',ref:'Tirmidhi n°3426'},
  // MOSQUEE
  {id:'d11',cat:'Mosquée',t:'En entrant',ar:'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',fr:'Ô Allah, ouvre-moi les portes de Ta miséricorde.',ref:'Muslim n°713'},
  {id:'d12',cat:'Mosquée',t:'En sortant',ar:'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',fr:'Ô Allah, je Te demande de Ta grâce.',ref:'Muslim n°713'},
  // TOILETTES
  {id:'d13',cat:'Toilettes',t:'En entrant',ar:'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',fr:'Ô Allah, je cherche refuge en Toi contre les démons mâles et femelles.',ref:'Bukhari n°142'},
  {id:'d14',cat:'Toilettes',t:'En sortant',ar:'غُفْرَانَكَ',fr:'(Je Te demande) Ton pardon.',ref:'Abu Dawud n°30'},
  // VOYAGE
  {id:'d15',cat:'Voyage',t:'En montant dans un véhicule',ar:'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ',fr:'Gloire à Celui qui nous a soumis cela alors que nous n\'en étions pas capables, et c\'est vers notre Seigneur que nous retournerons.',ref:'Muslim n°1342'},
  {id:'d16',cat:'Voyage',t:'Du\'a du voyageur',ar:'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَٰذَا الْبِرَّ وَالتَّقْوَى',fr:'Ô Allah, nous Te demandons dans ce voyage la piété et la crainte.',ref:'Muslim n°1342'},
  // PLUIE
  {id:'d17',cat:'Pluie',t:'Quand il pleut',ar:'اللَّهُمَّ صَيِّبًا نَافِعًا',fr:'Ô Allah, (envoie-nous) une pluie bénéfique.',ref:'Bukhari n°1032'},
  // MALADIE
  {id:'d18',cat:'Maladie',t:'Pour le malade',ar:'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِهِ وَأَنْتَ الشَّافِي',fr:'Ô Allah, Seigneur des gens, éloigne la souffrance, guéris-le, Tu es le Guérisseur.',ref:'Bukhari n°5742'},
  {id:'d19',cat:'Maladie',t:'Quand on est malade',ar:'لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللهُ',fr:'Pas de problème, c\'est une purification, si Allah le veut.',ref:'Bukhari n°3616'},
  // MORT
  {id:'d20',cat:'Décès',t:'À l\'annonce d\'un décès',ar:'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي',fr:'Nous appartenons à Allah et c\'est vers Lui que nous retournons. Ô Allah, récompense-moi dans mon malheur.',ref:'Muslim n°918'},
  // STRESS & ANGOISSE
  {id:'d21',cat:'Angoisse',t:'En période de détresse',ar:'لَا إِلَٰهَ إِلَّا اللهُ الْعَظِيمُ الْحَلِيمُ لَا إِلَٰهَ إِلَّا اللهُ رَبُّ الْعَرْشِ الْعَظِيمِ',fr:'Il n\'y a de divinité qu\'Allah le Grand le Clément. Il n\'y a de divinité qu\'Allah le Seigneur du Trône immense.',ref:'Bukhari n°6346'},
  {id:'d22',cat:'Angoisse',t:'Du\'a de Yunus (Jonas)',ar:'لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',fr:'Il n\'y a de divinité que Toi, gloire à Toi, j\'ai été parmi les injustes.',ref:'Tirmidhi n°3505'},
  // DETTE & SOUCIS
  {id:'d23',cat:'Soucis',t:'Contre les dettes',ar:'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',fr:'Ô Allah, rends-moi indépendant par Ton licite de Ton illicite, et enrichis-moi par Ta grâce de tout autre que Toi.',ref:'Tirmidhi n°3563'},
  // PARENTS
  {id:'d24',cat:'Famille',t:'Pour les parents',ar:'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',fr:'Ô mon Seigneur, aie pitié d\'eux comme ils m\'ont élevé dans ma petite enfance.',ref:'Al-Isra 17:24'},
  // ISTIGHFAR
  {id:'d25',cat:'Repentir',t:'Istighfar général',ar:'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الْغَفُورُ',fr:'Mon Seigneur, pardonne-moi et accepte mon repentir, Tu es Celui qui accepte le repentir, le Pardonneur.',ref:'Abu Dawud n°1516'},
];

const SURAHS_LOCAL = [
  {id:1,name_simple:"Al-Fatiha",name_arabic:"الفاتحة",translated_name:{name:"L'Ouverture"},verses_count:7,revelation_place:"makkah"},
  {id:2,name_simple:"Al-Baqara",name_arabic:"البقرة",translated_name:{name:"La Vache"},verses_count:286,revelation_place:"madinah"},
  {id:3,name_simple:"Al-Imran",name_arabic:"آل عمران",translated_name:{name:"La Famille d'Imran"},verses_count:200,revelation_place:"madinah"},
  {id:4,name_simple:"An-Nisa",name_arabic:"النساء",translated_name:{name:"Les Femmes"},verses_count:176,revelation_place:"madinah"},
  {id:5,name_simple:"Al-Ma'idah",name_arabic:"المائدة",translated_name:{name:"La Table Servie"},verses_count:120,revelation_place:"madinah"},
  {id:6,name_simple:"Al-An'am",name_arabic:"الأنعام",translated_name:{name:"Les Bestiaux"},verses_count:165,revelation_place:"makkah"},
  {id:7,name_simple:"Al-A'raf",name_arabic:"الأعراف",translated_name:{name:"Les Murailles"},verses_count:206,revelation_place:"makkah"},
  {id:8,name_simple:"Al-Anfal",name_arabic:"الأنفال",translated_name:{name:"Les Butins"},verses_count:75,revelation_place:"madinah"},
  {id:9,name_simple:"At-Tawbah",name_arabic:"التوبة",translated_name:{name:"Le Repentir"},verses_count:129,revelation_place:"madinah"},
  {id:10,name_simple:"Yunus",name_arabic:"يونس",translated_name:{name:"Jonas"},verses_count:109,revelation_place:"makkah"},
  {id:11,name_simple:"Hud",name_arabic:"هود",translated_name:{name:"Houd"},verses_count:123,revelation_place:"makkah"},
  {id:12,name_simple:"Yusuf",name_arabic:"يوسف",translated_name:{name:"Joseph"},verses_count:111,revelation_place:"makkah"},
  {id:13,name_simple:"Ar-Ra'd",name_arabic:"الرعد",translated_name:{name:"Le Tonnerre"},verses_count:43,revelation_place:"madinah"},
  {id:14,name_simple:"Ibrahim",name_arabic:"إبراهيم",translated_name:{name:"Abraham"},verses_count:52,revelation_place:"makkah"},
  {id:15,name_simple:"Al-Hijr",name_arabic:"الحجر",translated_name:{name:"Al-Hijr"},verses_count:99,revelation_place:"makkah"},
  {id:16,name_simple:"An-Nahl",name_arabic:"النحل",translated_name:{name:"Les Abeilles"},verses_count:128,revelation_place:"makkah"},
  {id:17,name_simple:"Al-Isra",name_arabic:"الإسراء",translated_name:{name:"Le Voyage Nocturne"},verses_count:111,revelation_place:"makkah"},
  {id:18,name_simple:"Al-Kahf",name_arabic:"الكهف",translated_name:{name:"La Caverne"},verses_count:110,revelation_place:"makkah"},
  {id:19,name_simple:"Maryam",name_arabic:"مريم",translated_name:{name:"Marie"},verses_count:98,revelation_place:"makkah"},
  {id:20,name_simple:"Ta-Ha",name_arabic:"طه",translated_name:{name:"Ta-Ha"},verses_count:135,revelation_place:"makkah"},
  {id:21,name_simple:"Al-Anbiya",name_arabic:"الأنبياء",translated_name:{name:"Les Prophètes"},verses_count:112,revelation_place:"makkah"},
  {id:22,name_simple:"Al-Hajj",name_arabic:"الحج",translated_name:{name:"Le Pèlerinage"},verses_count:78,revelation_place:"madinah"},
  {id:23,name_simple:"Al-Mu'minun",name_arabic:"المؤمنون",translated_name:{name:"Les Croyants"},verses_count:118,revelation_place:"makkah"},
  {id:24,name_simple:"An-Nur",name_arabic:"النور",translated_name:{name:"La Lumière"},verses_count:64,revelation_place:"madinah"},
  {id:25,name_simple:"Al-Furqan",name_arabic:"الفرقان",translated_name:{name:"Le Critère"},verses_count:77,revelation_place:"makkah"},
  {id:26,name_simple:"Ash-Shu'ara",name_arabic:"الشعراء",translated_name:{name:"Les Poètes"},verses_count:227,revelation_place:"makkah"},
  {id:27,name_simple:"An-Naml",name_arabic:"النمل",translated_name:{name:"Les Fourmis"},verses_count:93,revelation_place:"makkah"},
  {id:28,name_simple:"Al-Qasas",name_arabic:"القصص",translated_name:{name:"Les Récits"},verses_count:88,revelation_place:"makkah"},
  {id:29,name_simple:"Al-Ankabut",name_arabic:"العنكبوت",translated_name:{name:"L'Araignée"},verses_count:69,revelation_place:"makkah"},
  {id:30,name_simple:"Ar-Rum",name_arabic:"الروم",translated_name:{name:"Les Romains"},verses_count:60,revelation_place:"makkah"},
  {id:31,name_simple:"Luqman",name_arabic:"لقمان",translated_name:{name:"Luqman"},verses_count:34,revelation_place:"makkah"},
  {id:32,name_simple:"As-Sajdah",name_arabic:"السجدة",translated_name:{name:"La Prosternation"},verses_count:30,revelation_place:"makkah"},
  {id:33,name_simple:"Al-Ahzab",name_arabic:"الأحزاب",translated_name:{name:"Les Coalisés"},verses_count:73,revelation_place:"madinah"},
  {id:34,name_simple:"Saba",name_arabic:"سبأ",translated_name:{name:"Saba"},verses_count:54,revelation_place:"makkah"},
  {id:35,name_simple:"Fatir",name_arabic:"فاطر",translated_name:{name:"Le Créateur"},verses_count:45,revelation_place:"makkah"},
  {id:36,name_simple:"Ya-Sin",name_arabic:"يس",translated_name:{name:"Ya-Sin"},verses_count:83,revelation_place:"makkah"},
  {id:37,name_simple:"As-Saffat",name_arabic:"الصافات",translated_name:{name:"Rangés en Rangs"},verses_count:182,revelation_place:"makkah"},
  {id:38,name_simple:"Sad",name_arabic:"ص",translated_name:{name:"Sad"},verses_count:88,revelation_place:"makkah"},
  {id:39,name_simple:"Az-Zumar",name_arabic:"الزمر",translated_name:{name:"Les Groupes"},verses_count:75,revelation_place:"makkah"},
  {id:40,name_simple:"Ghafir",name_arabic:"غافر",translated_name:{name:"Celui Qui Pardonne"},verses_count:85,revelation_place:"makkah"},
  {id:41,name_simple:"Fussilat",name_arabic:"فصلت",translated_name:{name:"Détaillé"},verses_count:54,revelation_place:"makkah"},
  {id:42,name_simple:"Ash-Shura",name_arabic:"الشورى",translated_name:{name:"La Consultation"},verses_count:53,revelation_place:"makkah"},
  {id:43,name_simple:"Az-Zukhruf",name_arabic:"الزخرف",translated_name:{name:"L'Ornement"},verses_count:89,revelation_place:"makkah"},
  {id:44,name_simple:"Ad-Dukhan",name_arabic:"الدخان",translated_name:{name:"La Fumée"},verses_count:59,revelation_place:"makkah"},
  {id:45,name_simple:"Al-Jathiyah",name_arabic:"الجاثية",translated_name:{name:"L'Agenouillée"},verses_count:37,revelation_place:"makkah"},
  {id:46,name_simple:"Al-Ahqaf",name_arabic:"الأحقاف",translated_name:{name:"Les Dunes"},verses_count:35,revelation_place:"makkah"},
  {id:47,name_simple:"Muhammad",name_arabic:"محمد",translated_name:{name:"Muhammad"},verses_count:38,revelation_place:"madinah"},
  {id:48,name_simple:"Al-Fath",name_arabic:"الفتح",translated_name:{name:"La Victoire"},verses_count:29,revelation_place:"madinah"},
  {id:49,name_simple:"Al-Hujurat",name_arabic:"الحجرات",translated_name:{name:"Les Appartements"},verses_count:18,revelation_place:"madinah"},
  {id:50,name_simple:"Qaf",name_arabic:"ق",translated_name:{name:"Qaf"},verses_count:45,revelation_place:"makkah"},
  {id:51,name_simple:"Adh-Dhariyat",name_arabic:"الذاريات",translated_name:{name:"Les Vents Dispersants"},verses_count:60,revelation_place:"makkah"},
  {id:52,name_simple:"At-Tur",name_arabic:"الطور",translated_name:{name:"La Montagne"},verses_count:49,revelation_place:"makkah"},
  {id:53,name_simple:"An-Najm",name_arabic:"النجم",translated_name:{name:"L'Étoile"},verses_count:62,revelation_place:"makkah"},
  {id:54,name_simple:"Al-Qamar",name_arabic:"القمر",translated_name:{name:"La Lune"},verses_count:55,revelation_place:"makkah"},
  {id:55,name_simple:"Ar-Rahman",name_arabic:"الرحمن",translated_name:{name:"Le Tout Miséricordieux"},verses_count:78,revelation_place:"madinah"},
  {id:56,name_simple:"Al-Waqi'ah",name_arabic:"الواقعة",translated_name:{name:"L'Événement"},verses_count:96,revelation_place:"makkah"},
  {id:57,name_simple:"Al-Hadid",name_arabic:"الحديد",translated_name:{name:"Le Fer"},verses_count:29,revelation_place:"madinah"},
  {id:58,name_simple:"Al-Mujadila",name_arabic:"المجادلة",translated_name:{name:"La Femme qui Discute"},verses_count:22,revelation_place:"madinah"},
  {id:59,name_simple:"Al-Hashr",name_arabic:"الحشر",translated_name:{name:"Le Rassemblement"},verses_count:24,revelation_place:"madinah"},
  {id:60,name_simple:"Al-Mumtahanah",name_arabic:"الممتحنة",translated_name:{name:"L'Éprouvée"},verses_count:13,revelation_place:"madinah"},
  {id:61,name_simple:"As-Saf",name_arabic:"الصف",translated_name:{name:"Le Rang"},verses_count:14,revelation_place:"madinah"},
  {id:62,name_simple:"Al-Jumu'ah",name_arabic:"الجمعة",translated_name:{name:"Le Vendredi"},verses_count:11,revelation_place:"madinah"},
  {id:63,name_simple:"Al-Munafiqun",name_arabic:"المنافقون",translated_name:{name:"Les Hypocrites"},verses_count:11,revelation_place:"madinah"},
  {id:64,name_simple:"At-Taghabun",name_arabic:"التغابن",translated_name:{name:"La Déception"},verses_count:18,revelation_place:"madinah"},
  {id:65,name_simple:"At-Talaq",name_arabic:"الطلاق",translated_name:{name:"Le Divorce"},verses_count:12,revelation_place:"madinah"},
  {id:66,name_simple:"At-Tahrim",name_arabic:"التحريم",translated_name:{name:"L'Interdiction"},verses_count:12,revelation_place:"madinah"},
  {id:67,name_simple:"Al-Mulk",name_arabic:"الملك",translated_name:{name:"La Royauté"},verses_count:30,revelation_place:"makkah"},
  {id:68,name_simple:"Al-Qalam",name_arabic:"القلم",translated_name:{name:"La Plume"},verses_count:52,revelation_place:"makkah"},
  {id:69,name_simple:"Al-Haqqah",name_arabic:"الحاقة",translated_name:{name:"La Réalité Imminente"},verses_count:52,revelation_place:"makkah"},
  {id:70,name_simple:"Al-Ma'arij",name_arabic:"المعارج",translated_name:{name:"Les Degrés"},verses_count:44,revelation_place:"makkah"},
  {id:71,name_simple:"Nuh",name_arabic:"نوح",translated_name:{name:"Noé"},verses_count:28,revelation_place:"makkah"},
  {id:72,name_simple:"Al-Jinn",name_arabic:"الجن",translated_name:{name:"Les Djinns"},verses_count:28,revelation_place:"makkah"},
  {id:73,name_simple:"Al-Muzzammil",name_arabic:"المزمل",translated_name:{name:"L'Enveloppé"},verses_count:20,revelation_place:"makkah"},
  {id:74,name_simple:"Al-Muddathir",name_arabic:"المدثر",translated_name:{name:"Le Revêtu"},verses_count:56,revelation_place:"makkah"},
  {id:75,name_simple:"Al-Qiyamah",name_arabic:"القيامة",translated_name:{name:"La Résurrection"},verses_count:40,revelation_place:"makkah"},
  {id:76,name_simple:"Al-Insan",name_arabic:"الإنسان",translated_name:{name:"L'Homme"},verses_count:31,revelation_place:"madinah"},
  {id:77,name_simple:"Al-Mursalat",name_arabic:"المرسلات",translated_name:{name:"Les Envoyés"},verses_count:50,revelation_place:"makkah"},
  {id:78,name_simple:"An-Naba",name_arabic:"النبأ",translated_name:{name:"La Nouvelle"},verses_count:40,revelation_place:"makkah"},
  {id:79,name_simple:"An-Nazi'at",name_arabic:"النازعات",translated_name:{name:"Les Arracheurs"},verses_count:46,revelation_place:"makkah"},
  {id:80,name_simple:"Abasa",name_arabic:"عبس",translated_name:{name:"Il Se Renfrogna"},verses_count:42,revelation_place:"makkah"},
  {id:81,name_simple:"At-Takwir",name_arabic:"التكوير",translated_name:{name:"L'Enroulement"},verses_count:29,revelation_place:"makkah"},
  {id:82,name_simple:"Al-Infitar",name_arabic:"الانفطار",translated_name:{name:"La Déchirure"},verses_count:19,revelation_place:"makkah"},
  {id:83,name_simple:"Al-Mutaffifin",name_arabic:"المطففين",translated_name:{name:"Les Fraudeurs"},verses_count:36,revelation_place:"makkah"},
  {id:84,name_simple:"Al-Inshiqaq",name_arabic:"الانشقاق",translated_name:{name:"L'Éclatement"},verses_count:25,revelation_place:"makkah"},
  {id:85,name_simple:"Al-Buruj",name_arabic:"البروج",translated_name:{name:"Les Constellations"},verses_count:22,revelation_place:"makkah"},
  {id:86,name_simple:"At-Tariq",name_arabic:"الطارق",translated_name:{name:"L'Astre Nocturne"},verses_count:17,revelation_place:"makkah"},
  {id:87,name_simple:"Al-A'la",name_arabic:"الأعلى",translated_name:{name:"Le Très-Haut"},verses_count:19,revelation_place:"makkah"},
  {id:88,name_simple:"Al-Ghashiyah",name_arabic:"الغاشية",translated_name:{name:"L'Enveloppante"},verses_count:26,revelation_place:"makkah"},
  {id:89,name_simple:"Al-Fajr",name_arabic:"الفجر",translated_name:{name:"L'Aube"},verses_count:30,revelation_place:"makkah"},
  {id:90,name_simple:"Al-Balad",name_arabic:"البلد",translated_name:{name:"La Cité"},verses_count:20,revelation_place:"makkah"},
  {id:91,name_simple:"Ash-Shams",name_arabic:"الشمس",translated_name:{name:"Le Soleil"},verses_count:15,revelation_place:"makkah"},
  {id:92,name_simple:"Al-Layl",name_arabic:"الليل",translated_name:{name:"La Nuit"},verses_count:21,revelation_place:"makkah"},
  {id:93,name_simple:"Ad-Duha",name_arabic:"الضحى",translated_name:{name:"La Matinée"},verses_count:11,revelation_place:"makkah"},
  {id:94,name_simple:"Ash-Sharh",name_arabic:"الشرح",translated_name:{name:"L'Épanouissement"},verses_count:8,revelation_place:"makkah"},
  {id:95,name_simple:"At-Tin",name_arabic:"التين",translated_name:{name:"Le Figuier"},verses_count:8,revelation_place:"makkah"},
  {id:96,name_simple:"Al-Alaq",name_arabic:"العلق",translated_name:{name:"La Coagulation"},verses_count:19,revelation_place:"makkah"},
  {id:97,name_simple:"Al-Qadr",name_arabic:"القدر",translated_name:{name:"La Nuit du Destin"},verses_count:5,revelation_place:"makkah"},
  {id:98,name_simple:"Al-Bayyinah",name_arabic:"البينة",translated_name:{name:"La Preuve"},verses_count:8,revelation_place:"madinah"},
  {id:99,name_simple:"Az-Zalzalah",name_arabic:"الزلزلة",translated_name:{name:"Le Séisme"},verses_count:8,revelation_place:"madinah"},
  {id:100,name_simple:"Al-Adiyat",name_arabic:"العاديات",translated_name:{name:"Les Coureurs"},verses_count:11,revelation_place:"makkah"},
  {id:101,name_simple:"Al-Qari'ah",name_arabic:"القارعة",translated_name:{name:"La Fracassante"},verses_count:11,revelation_place:"makkah"},
  {id:102,name_simple:"At-Takathur",name_arabic:"التكاثر",translated_name:{name:"La Rivalité"},verses_count:8,revelation_place:"makkah"},
  {id:103,name_simple:"Al-Asr",name_arabic:"العصر",translated_name:{name:"Le Temps"},verses_count:3,revelation_place:"makkah"},
  {id:104,name_simple:"Al-Humazah",name_arabic:"الهمزة",translated_name:{name:"Le Calomniateur"},verses_count:9,revelation_place:"makkah"},
  {id:105,name_simple:"Al-Fil",name_arabic:"الفيل",translated_name:{name:"L'Éléphant"},verses_count:5,revelation_place:"makkah"},
  {id:106,name_simple:"Quraysh",name_arabic:"قريش",translated_name:{name:"Quraysh"},verses_count:4,revelation_place:"makkah"},
  {id:107,name_simple:"Al-Ma'un",name_arabic:"الماعون",translated_name:{name:"Les Ustensiles"},verses_count:7,revelation_place:"makkah"},
  {id:108,name_simple:"Al-Kawthar",name_arabic:"الكوثر",translated_name:{name:"L'Abondance"},verses_count:3,revelation_place:"makkah"},
  {id:109,name_simple:"Al-Kafirun",name_arabic:"الكافرون",translated_name:{name:"Les Infidèles"},verses_count:6,revelation_place:"makkah"},
  {id:110,name_simple:"An-Nasr",name_arabic:"النصر",translated_name:{name:"Le Secours"},verses_count:3,revelation_place:"madinah"},
  {id:111,name_simple:"Al-Masad",name_arabic:"المسد",translated_name:{name:"Les Fibres"},verses_count:5,revelation_place:"makkah"},
  {id:112,name_simple:"Al-Ikhlas",name_arabic:"الإخلاص",translated_name:{name:"La Sincérité"},verses_count:4,revelation_place:"makkah"},
  {id:113,name_simple:"Al-Falaq",name_arabic:"الفلق",translated_name:{name:"L'Aube Naissante"},verses_count:5,revelation_place:"makkah"},
  {id:114,name_simple:"An-Nas",name_arabic:"الناس",translated_name:{name:"Les Hommes"},verses_count:6,revelation_place:"makkah"},
];
